[theme]
name = "plain"
[theme.overrides]
separator_fg = "#5f5f5f"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#3f3f3f"
idle_fg = "#bfbfbf"

[[block]]
block = "load"
format = "{1m}"
interval = 5

[[block]]
block = "bluetooth"
mac = "94:DB:56:A3:E0:71"
format = "{percentage}"
format_unavailable = ""

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
warning = 20
critical = 7
allow_missing = true
hide_missing = true

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 60
format = "%a %d-%b %H:%M(%z)"
locale = "es_ES"
